### PR TITLE
Add a extension pop-up design

### PR DESCRIPTION
**Pull request by MatiasIslaA**
I've added an extension pop-up design consistent with the site style.

### CODE REVIEW

**Comment by killergerbah** [comment]
Thank you. If you are up for the challenge and have the time, I wonder if you would be able to make the style closer to the Material UI styles? For example: https://material-ui.com/components/checkboxes/

**Comment by MatiasIslaA** [comment]
Sure! I'll be busy until Wednesday though. I'll try to send a pull request on Friday.
By the way, would it be ok if I try to help with the other issues you've added? Since I'm a beginner at coding this is a great opportunity for learning and I would love the challenge of contributing to this project.

**Comment by killergerbah** [comment]
Sure no problem, feel free to work on whichever issues you please. Thanks for contributing!

**Comment by MatiasIslaA** [comment]
> Thank you. If you are up for the challenge and have the time, I wonder if you would be able to make the style closer to the Material UI styles? For example: https://material-ui.com/components/checkboxes/

@killergerbah I suddenly got a little bit of free time so I tried it right away... something like this or would you prefer softer colors? The transition when you click lost quality in the gif but you can get a general idea of how it looks. I tried to mimic the big circle that forms when you hover like the one of Material UI but it looked excesive due to the small size of the box so I made it a little more discrete. If it's okay, tell me and I'll send the pull request.

 Alt Text

**Comment by killergerbah** [comment]
@MatiasIslaA Thanks! This looks really good. My only thought:
- Can the text next to the each checkbox be vertically aligned with the middle of the checkbox?

**Pull request merged**
